@startuml M3L
package utils{
    class Conversion{
        aconv: float
    }
  }
package molecular_dynamics{
    class MolecularDynamics{
        nsteps: integer
        frames: list
        timestep: float
        convertUnits()
        running()
        setFrame()
    }
    class Integration{
        nve()
    }
    class ForceField{
  }
}
package structure{
    class System{
      natom: integer
      acell: float
      bcell: float
      ccell: float
      volume: float
      temperature: float
      pressure: float
      setNatom()
      setVolume()
      ccp()
    }
    class Atom{
        atoms: list
        setAtom()
  }
}
Conversion <|-- Atom
Integration o-- ForceField
MolecularDynamics <|-- Integration
System <|-- Integration
Atom <|-- System
@enduml
