@startuml M3L
package utils{
    class Conversion{
        aconv: float
    }
  }
package molecular_dynamics{
    class MolecularDynamics{
        convertUnits()
        running()
    }
    class Integration{
        nve()
    }
    class ForceField{
  }
package structure{
    class System{
      natom: integer
      step: integer
      acell: float
      bcell: float
      ccell: float
      volume: float
      temperature: float
      pressure: float
      setVolume()
      setAtoms()
      setNAtoms()
    }
    class Atom{
        atoms: list
    }
  }
}
Conversion <|-- Atom
Integration o-- ForceField
MolecularDynamics <|-- Integration
System <|-- Integration
Atom <|-- System
@enduml
